CREATE DATABASE TrelloDb
GO

USE TrelloDb
GO

CREATE TABLE BoardsAR
(
	BoardARId NVARCHAR(256) NOT NULL PRIMARY KEY
)

CREATE TABLE BoardsRenameHistory
(
	BoardHistoryId INT NOT NULL PRIMARY KEY IDENTITY(1,1),
	Name NVARCHAR(255) NOT NULL,
	BoardARId NVARCHAR(256) NOT NULL,
	RenameDate DATETIME NOT NULL DEFAULT GETDATE(),
	CONSTRAINT FK_BoardARId FOREIGN KEY (BoardARId) REFERENCES BoardsAR(BoardARId)
)

CREATE TABLE ColumnArId
(
	BoardColumnARId NVARCHAR(256) NOT NULL PRIMARY KEY
)

CREATE TABLE BoardColumnsRenameHistory
(
	Id INT IDENTITY(1,1) PRIMARY KEY,
	BoardColumnId NVARCHAR(256) NOT NULL,
	Name NVARCHAR(255) NOT NULL,
	RenameDate DATETIME NOT NULL DEFAULT GETDATE(),
	CONSTRAINT FK_BoardId FOREIGN KEY (BoardColumnId) REFERENCES BoardsAR(BoardARId),
	ColumnArId NVARCHAR(256) NOT NULL,
	CONSTRAINT FK_ColumnId FOREIGN KEY (ColumnArId) REFERENCES ColumnArId(BoardColumnARId)
)

CREATE TABLE CardAR
(
	CardARId NVARCHAR(256) NOT NULL PRIMARY KEY
)

CREATE TABLE CardContentChangeHistory		
(
	Id INT PRIMARY KEY IDENTITY(1,1),
	CardId NVARCHAR(256) NOT NULL,
	CardContent NVARCHAR(255) NOT NULL,
	RenameDate DATETIME NOT NULL DEFAULT GETDATE(),
	CONSTRAINT FK_CardId FOREIGN KEY (CardId) REFERENCES CardAR(CardARId)
)

CREATE TABLE CardMoveHistory		
(
	Id INT NOT NULL PRIMARY KEY IDENTITY(1,1),
	CardId NVARCHAR(256) NOT NULL,
	MoveDate DATETIME NOT NULL DEFAULT GETDATE(),
	ToBoardColumnId NVARCHAR(256) NOT NULL,
	CONSTRAINT FK_CardMovementHistory_CardId FOREIGN KEY (CardId) REFERENCES CardAR(CardARId),
	CONSTRAINT FK_ToBoardColumnId FOREIGN KEY (ToBoardColumnId) REFERENCES ColumnArId(BoardColumnARId)
)
GO




SELECT * FROM BoardsAR
SELECT * FROM BoardsRenameHistory

SELECT * FROM ColumnArId
SELECT * FROM BoardColumnsRenameHistory

SELECT * FROM CardAR
SELECT * FROM CardContentChangeHistory
SELECT * FROM CardMoveHistory
GO